name: Render Bot Scheduler

on:
  schedule:
    - cron: '30 16 * * *' # Raat 10:00 PM IST
    - cron: '30 03 * * *' # Subah 09:00 AM IST
  workflow_dispatch:      # Manual button ke liye

jobs:
  manage-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Action
        run: |
          # IST Time Calculation
          H=$(date -u -d "+5 hours +30 minutes" +%H)
          
          # Check: Agar raat ke 10 baje (22) se subah 9 baje (09) ke beech ka time hai
          if [ $H -ge 22 ] || [ $H -lt 09 ]; then
            ACTION="suspend"
          else
            ACTION="resume"
          fi
          
          echo "Current IST Hour: $H | Action: $ACTION"

          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/$ACTION" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               -H "Accept: application/json"
